---
- hosts: centos
  user: user
  sudo: yes
  connection: ssh
  gather_facts: no 
  tasks: 
       - name: Installing Apache
         yum: pkg=httpd state=latest
       - name: checking status of httpd
         command: systemctl status httpd
         register: result 
         until: result.stdout.find("active (running)") != 1
         retries: 4
         delay: 4 
       - debug: var=result
         
