---
- hosts: local
  sudo: yes
  user: sagar
  connection: ssh
  gather_facts: no
  vars_prompt:
    - name: name
      prompt: Enter package name?
      private: no
  tasks:
    - name: Installing the Packages
      apt: pkg={{ name }} state=absent 
  
