--- # Ansible 2.5 SETFACT
- hosts: centos
  remote_user: root
  vars:
    course: Ansible2.5
  tasks:
  - name: Using setfact
    set_fact:
       singlefact: Fact
  - debug: msg={{ course }}
  - debug: msg={{ singlefact }}
  - name: Change the veriables 
    set_fact:
       single_fact: Ansible1.9.2 Completed
  - debug: msg={{ single_fact }}
    
