pipeline {
        agent any
                stages {
                        stage('Bulid'){
                                steps { 
                                        echo 'Bulid started'
                                        python flaskapp.py
                                }
}
}
