pipeline {
  agent any
  stages {
   stage('Build') {
    steps {
     echo 'Running Build'
     sudo yum update -y
     sudo yum install python-pip
     sudo pip install flask
     mkdir ~/flaskapp
     cd flaskapp
     vim flaskapp.py
     from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
  return 'Hello from Flask!'

if __name__ == '__main__':
  app.run()

   }
  }
 }
}
~
~
